### ISSUE TITLE
LaTeX equations should use (α^0)_(p,P_GFP), not α_(p,P_GFP)

### ISSUE THREAD

**Issue by hgscott** [TASBE/CRISPRi-promoters#1]
In the Supplementary S1, the production rate symbol α_(p,P_GFP)of formula (17), (25), (31), (41), (47), (59), (65), (79), (85), (101), and (107) should be changed to the maximal production rate symbol  (α^0)_(p,P_GFP).

**Comment by hgscott** [comment]
I am unsure how to do this directly in the latex_generation script, since I don't want to change all of the alpha_ps (e.g. the alpha_p,P_dCas9 should still be alpha_p, not alpha^0_p.

So, I want to add an addendum to the `sbol_to_latex.py` script that will change the output of the latex_generation function before saving it to the `generated_equations.tex` file.

But, I can no longer run my existing `sbol_to_latex.py script`, I am getting an error due to the tyto package.

The simplest recreation of the error, is when I run:
```
import tyto

tyto.SBO.systems_biology_representation
```

I get the following error message:
```
Traceback (most recent call last):
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/socket.py", line 844, in create_connection
    raise err
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/tyto/tyto.py", line 47, in __getattr__
    return self.__getattribute__('get_uri_by_term')(name)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/tyto/tyto.py", line 123, in get_uri_by_term
    uri = self._handler('get_uri_by_term', exception, sanitized_term)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/tyto/tyto.py", line 72, in _handler
    response = method(self, *args)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/tyto/endpoint/endpoint.py", line 81, in get_uri_by_term
    response = self.query(ontology, query, error_msg)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/tyto/endpoint/endpoint.py", line 298, in query
    response = super().query(ontology, sparql, err_msg)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/tyto/endpoint/endpoint.py", line 231, in query
    response = self._endpoint.query()
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/SPARQLWrapper/Wrapper.py", line 960, in query
    return QueryResult(self._query())
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/site-packages/SPARQLWrapper/Wrapper.py", line 926, in _query
    response = urlopener(request)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/Users/hscott/Documents/APT/CRISPRi-promoters/env/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 61] Connection refused>
```

So for now, I have corrected the equations manually in a new file called `manually_edited_equations.tex`, but I would like to revisit this so that the equations are fixed in the automatic generation.

**Comment by hgscott** [comment]
To debug why tyto isn't working for me, I made a completely new conda environment, `tyto-test`, with: `conda create -n tyto-test python=3`

Then I installed tyto wth pip.

Then I ran my minimal test from above:
<img width="837" alt="image" src="https://github.com/user-attachments/assets/c8ec0eea-a6dc-4008-b390-635526a4c4e6">

And I got the same error, ending with:
<img width="978" alt="image" src="https://github.com/user-attachments/assets/7c7b7cbd-1024-4923-a9fe-d0ee2d1214b0">

**Comment by hgscott** [comment]
On safari, when I try to navigate to Ontobee.org, I get an error that the server is down:
<img width="905" alt="image" src="https://github.com/user-attachments/assets/fb362601-4719-4240-b89f-fb6330b27f31">

**Comment by hgscott** [comment]
Ontobee is now back up, and so we can now do the pretty fix.
![image](https://github.com/user-attachments/assets/7d6b8dd5-bc17-48de-802a-c394c9abedce)
